# Generated by Django 5.0.6 on 2024-07-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('teacher_image', models.ImageField(upload_to='')),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=10)),
                ('subject_specialisation', models.CharField(max_length=30)),
                ('bio', models.TextField()),
                ('education_level', models.CharField(max_length=20)),
            ],
        ),
    ]
