# Generated by Django 5.0.6 on 2024-07-07 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_course_id'),
        ('teacher', '0002_teacher_course_taught_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='course_taught_id',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject_specialisation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subject_specialisation', to='course.course'),
        ),
    ]
