# Generated by Django 5.0.6 on 2024-07-07 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0001_initial'),
        ('course', '0002_course_course_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='class_id',
        ),
        migrations.AddField(
            model_name='class',
            name='class_id_taken',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='course_id_taken', to='course.course'),
        ),
    ]
