# Generated by Django 5.0.6 on 2024-07-07 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0002_remove_class_class_id_class_class_id_taken'),
        ('course', '0003_alter_course_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_id_taken',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_id_taken', to='course.course'),
        ),
    ]
