# Generated by Django 5.0.6 on 2024-07-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=30)),
                ('course_description', models.TextField()),
                ('class_starting_time', models.TimeField()),
                ('course_instructor', models.CharField(max_length=20)),
            ],
        ),
    ]
