# Generated by Django 5.0.6 on 2024-07-07 09:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_id',
            field=models.PositiveSmallIntegerField(default=5),
            preserve_default=False,
        ),
    ]
